version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      # volumes: - "C:\Users\Maria\Desktop\Sweng github\MSE_repo"
      - C:\Users\Maria\Desktop\Sweng github\MSE_repo
      # - /somedirectory:/data/db  # you need to mondify this
      # gives you acess to the data after the mongo has run
    ports:
      - 27017:27017
    restart: unless-stopped
